#!/usr/bin/python3
def raise_exception():
    test = 'hello'
    a = test + 1
